title: "Alec Gallo"
author: "Alec Gallo"
description: "University California-San Francisco, UniKonstanz"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "alecgallo.md", title: "CV"} 
  - {file: "research.md", title: "Research"}
  - {file: "outside_the_lab.md", title: "Outside the lab"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "alecgdrcmr.dk"}
  - {title: Github, icon: github, url: "https://github.com/alecgallo/"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/alecgallo/"}
  - {title: Google scholar, icon: <font-awesome-icon icon="google-scholar" />, url: "https://scholar.google.com.hk/citations?hl=en&pli=1&user=OeHmqp8AAAAJ"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
